---
- include: edge-prerequisite-playbook.yaml
- hosts: apigee
  vars:
    boot_strap_url: https://software.apigee.com
    boot_strap_file_name: bootstrap_4.16.05.sh
    apigee_dest_path: /tmp/apigee
  tasks:
  - name: Get BootstrapFile
    get_url: url={{boot_strap_url}}/{{boot_strap_file_name}} dest={{apigee_dest_path}}/{{boot_strap_file_name}}
    sudo: yes
  - name: install apigee service
    command: "bash {{apigee_dest_path}}/{{boot_strap_file_name}} apigeeuser={{ apigee_user }} apigeepassword={{ apigee_password }} JAVA_FIX=I"
    sudo: yes
  - name: Install Apigee setup
    command: "/opt/apigee/apigee-service/bin/apigee-service apigee-setup install"
    sudo: yes
- include: edge-components-setup-playbook.yaml
