---
- hosts: apigee
  vars:
    apigee_dest_path: /tmp/apigee
  tasks:
  - name: Get BootstrapFile
    command: "curl -o {{apigee_dest_path}}/bootstrap_{{ version }}.sh {{ softwareRepo }}/bootstrap_{{ version }}.sh -u {{apigee_user}}:{{apigee_password}}"
    sudo: yes
  - name: install apigee service
    command: "bash {{apigee_dest_path}}/bootstrap_{{ version }}.sh apigeeuser={{ apigee_user }} apigeepassword={{ apigee_password }} apigeestage=e2e apigeerepohost=ap-repo.aeip.apigee.net"
    sudo: yes
  - name: Install Apigee setup
    command: "/opt/apigee/apigee-service/bin/apigee-service apigee-setup install"
    sudo: yes